CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE knowledge_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    content TEXT NOT NULL,
    domain VARCHAR(80) NOT NULL,
    source VARCHAR(120) NOT NULL,
    tags VARCHAR(300),
    status VARCHAR(32) NOT NULL,
    review_comment VARCHAR(500),
    reviewer VARCHAR(80),
    chunk_count INTEGER NOT NULL DEFAULT 0,
    index_version BIGINT NOT NULL DEFAULT 0,
    source_hash VARCHAR(64),
    created_by VARCHAR(80) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE knowledge_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES knowledge_documents(id) ON DELETE CASCADE,
    chunk_index INTEGER NOT NULL,
    document_version BIGINT NOT NULL,
    content TEXT NOT NULL,
    embedding TEXT,
    content_hash VARCHAR(64) NOT NULL,
    token_count INTEGER NOT NULL,
    heading_path VARCHAR(500),
    locator VARCHAR(200),
    page_number INTEGER,
    embedding_model VARCHAR(120) NOT NULL,
    CONSTRAINT uk_chunk_document_version_index UNIQUE(document_id, document_version, chunk_index)
);

CREATE TABLE import_batches (
    id VARCHAR(40) PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    domain VARCHAR(80) NOT NULL,
    created_by VARCHAR(80) NOT NULL,
    tags VARCHAR(300),
    total_files INTEGER NOT NULL DEFAULT 0,
    processed_files INTEGER NOT NULL DEFAULT 0,
    succeeded_files INTEGER NOT NULL DEFAULT 0,
    failed_files INTEGER NOT NULL DEFAULT 0,
    worker_id VARCHAR(100),
    lease_until TIMESTAMP,
    next_attempt_at TIMESTAMP,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(800),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE import_file_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id VARCHAR(40) NOT NULL REFERENCES import_batches(id) ON DELETE CASCADE,
    original_name VARCHAR(255) NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    content_hash VARCHAR(64) NOT NULL,
    storage_deduplicated BOOLEAN NOT NULL DEFAULT FALSE,
    detected_type VARCHAR(160),
    size_bytes BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    extracted_characters INTEGER NOT NULL DEFAULT 0,
    document_id BIGINT REFERENCES knowledge_documents(id),
    error_message VARCHAR(800),
    retry_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE question_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id VARCHAR(40) NOT NULL UNIQUE,
    question VARCHAR(1000) NOT NULL,
    answer TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL,
    latency_ms BIGINT NOT NULL,
    accepted BOOLEAN,
    bad_case BOOLEAN NOT NULL,
    bad_reason VARCHAR(500),
    source_snapshot TEXT,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE outbox_events (
    id VARCHAR(40) PRIMARY KEY,
    topic VARCHAR(120) NOT NULL,
    event_key VARCHAR(120) NOT NULL,
    event_type VARCHAR(80) NOT NULL,
    payload VARCHAR(1000) NOT NULL,
    status VARCHAR(20) NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP,
    published_at TIMESTAMP,
    last_error VARCHAR(800),
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_document_status_domain ON knowledge_documents(status, domain);
CREATE INDEX idx_document_title_trgm ON knowledge_documents USING GIN(title gin_trgm_ops);
CREATE INDEX idx_chunk_document ON knowledge_chunks(document_id);
CREATE INDEX idx_chunk_content_hash ON knowledge_chunks(content_hash);
CREATE INDEX idx_chunk_content_trgm ON knowledge_chunks USING GIN(content gin_trgm_ops);
CREATE INDEX idx_import_batch_claim ON import_batches(status, next_attempt_at, lease_until);
CREATE INDEX idx_import_file_batch_status ON import_file_tasks(batch_id, status);
CREATE INDEX idx_question_bad_case_created ON question_logs(bad_case, created_at DESC);
CREATE INDEX idx_outbox_publish ON outbox_events(status, next_attempt_at, created_at);
